disabled_rules: # rule identifiers to exclude from running
 - line_length
# - trailing_whitespace
# - vertical_whitespace
 - trailing_newline
 - identifier_name
 - force_cast
opt_in_rules: # some rules are only opt-in
 - sorted_imports
 #- no_grouping_extension
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods